In [9]:
# koleksiyonlar
# liste(list) []
# sözlük(dictionary){}
# demet(tuple) ()

#liste
l1=["ayşe",20,True,10.5] #eleman(item)
print(l1[2])
print(l1[3])
#atama (assigment)
l1[2]=False
print(l1[2])

#ekleme(append)
l1.append(38)
print(l1)

for eleman in l1:
    print(eleman)

l2=[[1,2,3],[4,5,6]]
l2[1][1]=100
print(l2[1][1])


True
10.5
False
['ayşe', 20, False, 10.5, 38]
ayşe
20
False
10.5
38
100


In [19]:
#sözlükler
#anahtar değer
yaslar={3:40,"kayra":14,"beylem":36,"saner":13,"armina":15,"beylem":30,"beylem":25,"beylem":40}

print(yaslar["beylem"])
print(yaslar)

40
{3: 40, 'kayra': 14, 'beylem': 40, 'saner': 13, 'armina': 15}


In [28]:
#numpy
import numpy as np

nl1=np.array([1,2,10,20])
print(nl1.dtype)
nl2=np.array([[1,2,3],[4,5,6]])
print(f"boyut={nl2.ndim}")
print(f"adet={nl2.size}")
print(f"şekil={nl2.shape}")

nl3=np.zeros((3,4))
print(nl3)
print("*"*30)
nl4=np.ones((2,3,4))
print(nl4)
nl5=np.full((3,5),0.8)
print(nl5)

int64
boyut=2
adet=6
şekil=(2, 3)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
******************************
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[0.8 0.8 0.8 0.8 0.8]
 [0.8 0.8 0.8 0.8 0.8]
 [0.8 0.8 0.8 0.8 0.8]]


In [39]:
na1=np.array([2,5,9,10])
na2=np.array([15,50,8,11])
na3=np.array([[1],[2],[3],[4]])
print(na1*2-2)
print(na1+na2)
print("*"*30)
print(na1+na3)
print("max=",na2.max())
print("min=",na2.min())
print("mean=",na2.mean())
print("standart sapma=",na2.std())
print("toplam=",na2.sum())

[ 2  8 16 18]
[17 55 17 21]
******************************
[[ 3  6 10 11]
 [ 4  7 11 12]
 [ 5  8 12 13]
 [ 6  9 13 14]]
max= 50
min= 8
mean= 21.0
standart sapma= 16.926310879810757
toplam= 84
